name: Build, Push & Deploy Laravel to EC2

on:
  workflow_run:
    workflows: ["Run Laravel Tests"]
    types:
      - completed

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_KEY }}

      - name: Build Laravel Docker image
        working-directory: smart-fridge-server
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/smart_fridge_laravel:latest .

      - name: Push image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/smart_fridge_laravel:latest

  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST_STAGING }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/smart_fridge
            echo "Stopping current containers..."
            sudo docker compose down
            echo "Cleaning unused resources..."
            sudo docker system prune -f
            echo "Pulling latest image..."
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/smart_fridge_laravel:latest
            echo "Starting containers..."
            sudo docker compose up -d